---
- name: Ubuntu Desktop Setup with Packages and Configuration
  hosts: localhost
  connection: local



  vars:
    buildessentials:
      - wget
      - curl
      - gpg
      - ca-certificates

    packages:
      - tmux
      - neovim
      - nmap
      - curl
      - bat
      - tor
      - zsh
      #- zsh-syntax-highlighting
      #- zsh-autosuggestions
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-lascaille
      - regolith-look-ayu-dark
      - i3xrocks-battery
      - i3xrocks-volume
      - i3xrocks-cpu-usage
      - i3xrocks-memory
      - i3xrocks-microphone
      - code
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

    oh_my_zsh_dir: "{{ ansible_env.HOME }}/.oh-my-zsh"
    zsh_plugins_dir: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins"

  tasks:
    - name: Install buildessentials
      become: yes
      apt:
        name: "{{ buildessentials }}"
        state: present
        update_cache: yes
      tags: buildessentials



    - name: Docker key add
      become: yes
      block:
        - name: docker | add key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            
        - name: docker | apt source
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

    - name: VSCode key add
      become: yes
      block:
        - name: VSCode | add key
          ansible.builtin.get_url:
            url: https://packages.microsoft.com/keys/microsoft.asc
            dest: /etc/apt/keyrings/microsoft.asc
            
        - name: VSCode | apt source
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
            state: present


    - name: Regolith key add
      become: yes
      block:
        - name: regolith | add key
          ansible.builtin.get_url:
            url: https://archive.regolith-desktop.com/regolith.key
            dest: /usr/share/keyrings/regolith-archive-keyring.gpg
            mode: '0644'
          register: regolith_key

        - name: regolith | convert key to gpg format if needed
          ansible.builtin.command: >
            gpg --dearmor /usr/share/keyrings/regolith-archive-keyring.gpg
            -o /usr/share/keyrings/regolith-archive-keyring.gpg
          when: regolith_key.changed
          args:
            creates: /usr/share/keyrings/regolith-archive-keyring.gpg

        - name: regolith | add apt repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://archive.regolith-desktop.com/ubuntu/stable noble v3.2"
            filename: regolith
            state: present

        - name: regolith | update apt cache
          ansible.builtin.apt:
            update_cache: yes



    - name: Update apt cache and install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      tags: packages
      become: yes

## Oh-my-zsh config

    - name: Set zsh as default shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      tags: zsh

    - name: Install Oh My Zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ oh_my_zsh_dir }}"
        update: yes
      tags: ohmyzsh

    - name: Ensure plugins directory exists
      file:
        path: "{{ zsh_plugins_dir }}"
        state: directory
      tags: zsh_plugins

    - name: Install zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ zsh_plugins_dir }}/zsh-autosuggestions"
        update: yes
      tags: zsh_plugins

    - name: Install zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ zsh_plugins_dir }}/zsh-syntax-highlighting"
        update: yes
      tags: zsh_plugins

    - name: Install you-should-use plugin
      git:
        repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
        dest: "{{ zsh_plugins_dir }}/you-should-use"
        update: yes
      tags: zsh_plugins

    - name: Configure .zshrc with required plugins
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: '^plugins='
        line: "plugins=(git zsh-autosuggestions zsh-syntax-highlighting you-should-use sudo)"
        create: yes
        state: present
      tags: zshrc


## NEOVIM

    - name: Download LazyVim starter config for Neovim
      git:
        repo: https://github.com/LazyVim/starter
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        force: yes
      tags: nvim

    - name: Change ownership of nvim config
      file:
        path: "{{ ansible_env.HOME }}/.config/nvim"
        state: directory
        recurse: yes
        owner: "{{ ansible_user_id }}"
      tags: nvim

### DOCKER

    - name: Ensure Docker service is running
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('user') }}"
        groups: docker
        append: yes
      become: yes


#### REGOLITH Configuration

    - name: Ensure Regolith Xresources directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config/regolith3"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Set focused window border color and gaps in Xresources
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/regolith3/Xresources"
        block: |
          wm.border.focused.color: #800080
          wm.gaps.inner.size: 20
        create: yes
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'

    # - name: Reload Regolith look to apply changes
    #   become: yes
    #   shell: regolith-look refresh
      # environment:
      #   DISPLAY: ":0"
      #   XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid }}"
      # args:
      #   warn: false


